# eslint-disable yml/block-sequence 
name: Playwright Tests

on:
    push:
        branches: [CI/CD-Branch]
    pull_request:
        branches: [CI/CD-Branch]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: ⬇️ Checkout repository
                uses: actions/checkout@v4

            -   name: 🟢 Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 20
                    cache: "pnpm"

            -   name: ⬇️ Setup pnpm
                uses: pnpm/action-setup@v2
                with:
                    version: 8 # or the version you're using locally

            -   name: 📦 Install dependencies
                run: pnpm install

            -   name: ⬇️ Install Playwright browsers
                run: pnpm exec playwright install --with-deps

            -   name: 🧪 Run Playwright tests
                run: pnpm exec playwright test

            -   name: 📤 Upload Monocart HTML Report
                if: always()
                uses: actions/upload-artifact@v4
                with:
                    name: monocart-report
                    path: artifacts/test_reports/monocart-report
